### PR TITLE
Add checking not empty arguments

### PR DESCRIPTION
**Pull request by lukashes**
AnyArg() does not help if expected value should not be empty

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hi, **nil** is a valid argument. And this change, would be a backward incompatible change, which cannot be accepted. I do not wish to add any additional argument matchers in the library, since it provides a way to create such for specific use cases. there is a discussion concerning that: #72 and probably it would be better if people would just create a wiki page for specific argument matchers.

**Comment by l3pp4rd** [comment]
Haven't noticed that this is a separate arg matcher, but that does not change. the library will provide only one matcher and this is **AnyArg** all other matchers are for users to make for their own use - that is it.. I do not want to grow this into confusing number of options to choose from when matching an argument

**Comment by lukashes** [comment]
Hello, my request not about AnyArg or Any{Type}, but I understood that your library will not include nothing instead of **AnyArg**. Ok.

I would like to hear your opinion why users should use original values every time? For example, I have table with 20 columns (it is real case for me) and I need to check only one column with autogenerated uuid. Checking non empty value in this column - it is enough good decision, other values may be AnyArg, because I checked it before in another tests.

**Comment by l3pp4rd** [comment]
well just create the same **NotEmptyArg** in your tests and use it. because all you need is to satisfy sqlmock.Argument interface to achieve the behavior you prefer. If we start to put various argument matchers in sqlmock library soon it will grow into confusing numbers.

**Comment by lukashes** [comment]
Ok, thanks :)

**Pull request closed without merging**
