### PR TITLE
Additional test for rows

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
thanks again ;)

**Comment by gliptak** [comment]
@l3pp4rd Maybe a different ```err``` propagation would be better here instead of ```panic``` ...

**Comment by l3pp4rd** [comment]
on one hand maybe it would make sense to add an error [here](https://github.com/DATA-DOG/go-sqlmock/blob/master/rows.go#L58) but it would need to also return an error when a `QueryRow` is used.
On the other hand, the failure is during the setup of mock, which can only happen from tests and failing fast with panic also makes sense to prevent some confusion.

**Comment by gliptak** [comment]
The problem with ```panic``` is that it fails all tests in the  same file, which is not good user experience. Maybe ```t.Error``` could be called during setup or propagate when called (as above) with a description pointing back to the setup section?

**Comment by l3pp4rd** [comment]
I agree that it is not the best experience, but this library might not necessarily is used for tests. If we give a `testing.T` reference to sqlmock then we would break BC and restrict usage to testing. Which sounds like a bad idea in general. For example I use sqlmock for [godog cucumber tests](https://github.com/DATA-DOG/godog) and there is no `testing.T` ref.
The only idea comes to my mind is to propagate this error to QueryRows or QueryRow resulting error.

**Comment by gliptak** [comment]
@l3pp4rd I didn't know of the goal of not having ```testing.T``` as a dependency. My vote would be for the propagation of the error (even if it causes losing the code location reference).

**Pull request merged**
