### PR TITLE
Examples/go sql driver imports

### PR DESCRIPTION
**Pull request by theodesp**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
well, makes sense in a way. but there is an issue with that. `go mod` will lookup mysql as a dependency, which would cause it as a requirement for this library (unless I missing something). And in general the library has no dependencies.
So in the end I think it would be better to leave it as is, because it is an obvious error and user who wants to test the example would just figure this out.

The readme change is fine.

**Comment by theodesp** [comment]
OK I will keep the Readme change and remove the other ones

**Comment by theodesp** [comment]
@l3pp4rd PR updated

**Comment by l3pp4rd** [comment]
thanks ;)

**Pull request merged**
