### PR TITLE
migration from custom namedValue to driver.NamedValue

### PR DESCRIPTION
**Pull request by Apologiz**

### CODE REVIEW

**Comment by Apologiz** [comment]
build is failed because support **driver.NamedValue** appeared in Go 1.8.
I think this is not important, because if the project has an old version of Go, they will not update the library version.

**Comment by l3pp4rd** [comment]
Hi, thanks for the changes to support gorm and others, though backward compatibility is very important, if it can be preserved, it should. I do not want to create the v2 just for this minor change, which can be made backward compatible in general. Just move the functions related to files before go 1.8 and after.

**Comment by Apologiz** [comment]
@l3pp4rd, unfortunately, as you suggested, it will not work, because gorm inside has checks sql.NamedArg structure.

**Comment by Apologiz** [comment]
I doubt that those who did not upgrade Go to version 1.8+ will start updating the DATA-DOG/go-sqlmock library :)

**Comment by Apologiz** [comment]
@l3pp4rd, I added mammoth support and covered in tests :)

**Comment by l3pp4rd** [comment]
very good, thanks!

**Pull request merged**
