### PR TITLE
concurrency support, closes #20 and closes #9 and closes #15

### LINKED ISSUE #9: Package not usable with parallel tests
There is currently a data race when using go-sqlmock in two tests in parallel due to the way the API is currently designed. There is only ever one "mock" database and all operations are done on this. This means two tests cannot use this package in parallel. This is evidenced from the following data race in a package I am developing. I'm going to take a stab and changing the API to accommodate this.

    ==================
    WARNING: DATA RACE
    Read by goroutine 10:
      github.com/DATA-DOG/go-sqlmock.ExpectQuery()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/sqlmock.go:155 +0x138
      github.com/jnwhiteh/migration.setupVersioned()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:35 +0x22a
      github.com/jnwhiteh/migration.TestDowngradesUnsupported()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:61 +0x73
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Previous write by goroutine 8:
      github.com/DATA-DOG/go-sqlmock.(*conn).Close()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/connection.go:24 +0x266
      database/sql.(*driverConn).finalClose()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:310 +0x175
      database/sql.finalCloser.(database/sql.finalClose)·fm()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:398 +0x57
      database/sql.(*DB).Close()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:487 +0x6fa
      github.com/jnwhiteh/migration.TestFailingToGetCurrentVersion()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:54 +0x331
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Goroutine 10 (running) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    
    Goroutine 8 (finished) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    ==================
    ==================
    WARNING: DATA RACE
    Write by goroutine 10:
      github.com/DATA-DOG/go-sqlmock.ExpectQuery()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/sqlmock.go:156 +0x309
      github.com/jnwhiteh/migration.setupVersioned()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:35 +0x22a
      github.com/jnwhiteh/migration.TestDowngradesUnsupported()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:61 +0x73
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Previous write by goroutine 8:
      github.com/DATA-DOG/go-sqlmock.(*conn).Close()
          /Users/jnwhiteh/go/src/github.com/DATA-DOG/go-sqlmock/connection.go:25 +0x2d0
      database/sql.(*driverConn).finalClose()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:310 +0x175
      database/sql.finalCloser.(database/sql.finalClose)·fm()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:398 +0x57
      database/sql.(*DB).Close()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/database/sql/sql.go:487 +0x6fa
      github.com/jnwhiteh/migration.TestFailingToGetCurrentVersion()
          /Users/jnwhiteh/go/src/github.com/jnwhiteh/migration/migration_test.go:54 +0x331
      testing.tRunner()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:422 +0x10f
    
    Goroutine 10 (running) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    
    Goroutine 8 (finished) created at:
      testing.RunTests()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:504 +0xb46
      testing.Main()
          /usr/local/Cellar/go/1.3.3/libexec/src/pkg/testing/testing.go:435 +0xa2
      main.main()
          github.com/jnwhiteh/migration/_test/_testmain.go:61 +0xdc
    ==================
    PASS
    Found 2 data race(s)
    exit status 66
    FAIL	github.com/jnwhiteh/migration	1.105s

### LINKED ISSUE #13: Force errors in other places
I would like to force errors in other places such as:

```
http://golang.org/pkg/database/sql/#Rows.Scan
http://golang.org/pkg/database/sql/#Rows.Columns
```

Are there any plans about this?

### LINKED ISSUE #15: Expect Close to be called
It'd be nice if the mock rows struct would expect Close() to be called, either by default or with an ExpectClose() enabler. Most of the time the closing is deferred, but we want to test that it happens.

### LINKED ISSUE #20: duplicate driverConn close
Any function that calls `rows.Close()` causes a `sql: duplicate driverConn close` when calling `db.Close()` on the mock db object.

Sample code for illustration purposes

Sample function:
```go
type MyDatabase struct {
    sql.DB
}

func (db *MyDatabase) GetThing(thing string) (data []byte, err error) {
    stmt := "SELECT ..."
    rows, err := db.Query(stmt, thing) 
    if err != nil {
        return nil, err 
    }   
    defer rows.Close()
    ... 
}
```

Sample test:
```go
func TestMySQLGetTimestampKeyNoKey(t *testing.T) {
    db, _ := sqlmock.New()
    s := MyDatabase{DB: db}

    sqlmock.ExpectQuery(
        "SELECT `cipher`, `public` FROM `timestamp_keys` WHERE `gun`=\\?;",
    ).WithArgs("testGUN").WillReturnError(sql.ErrNoRows)

    foo, err = s.GetThing("testThing")
    ...

    err = db.Close()
    assert.Nil(t, err, "Expectation not met: %v", err)
}
```

Commenting out that `defer rows.Close()` stops the error being raised. I don't see anything in the go-sqlmock code that would make this happen and I don't have time to dig into it right now.

### LINKED ISSUE #22: FromCSVString does not handle null values
It would be nice if the docs mentioned this.
This library is very useful, btw.

### PR DESCRIPTION
**Pull request by l3pp4rd**
After some use cases and 

Refactor to support concurrency and multiple connections per mock database instance.
When this branch will be merged, there will be **BC** break and a new major version bump.

Solves the following issues:
- [x] parallel tests, any number of mock databases, closes #9 extends and closes #10 
- [x] since rows holds a connection reserved, allow to open any number of connections, closes #20 
- [x] allow to expect database close to be called, closes #15 
- [x] more expectations, for example allow for rows to return error at any point. closes #13 
- [x] deprecated methods: **RowsFromCSVString** will be removed
- [x] allow unordered expectation matching, support for goroutines, see [test](https://github.com/DATA-DOG/go-sqlmock/blob/refactor/sqlmock_test.go#L580).
- [x] all possible places where values may be changed, should be available for mocking.
- [x] more expressive errors
- [x] documentation updated
- [x] allow null values from csv string to be converted to nil. closes #22

### CODE REVIEW

**Comment by cristiangraz** [comment]
I'm testing this branch out but have a situation where I have two expectPrepare().expectExec().WithArgs().WillReturnResult() One of my queries runs in the method being tested, the other query runs in a goroutine launched from that method.

If I put in a non-valid value for one of the args in the goroutine query, I see the error returned from the stmt exec call in the function but the tests still pass. If I put a non-valid value in one of the args for the query that is in the function directly, a panic is thrown and the tests no longer pass. Here is the error format (... added by me): exec query 'update ...', args [...] does not match expected [...]

Should I be setting up my tests differently? Other than that I haven't noticed any other issues with the branch so far!

**Comment by l3pp4rd** [comment]
hi @cristiangraz thanks for trying the branch out, I will have a look at the test case you have encountered when I have time, cheers

**Comment by dgnorton** [comment]
@l3pp4rd can `ExpectQuery` be called multiple times before testing a function that will run several queries which are not part of a transaction?  It seems that only the query passed in the last call to `ExpectQuery` is actually expected.

**Comment by l3pp4rd** [comment]
hi @dgnorton it should register all expectations and run them in the same order, will add more test cases. thanks for trying out this branch ;)

**Comment by cristiangraz** [comment]
@l3pp4rd - would you consider support for a WildcardArg type that can be used in the WithArgs method? Here's the use case: I have a struct that gets converted to json as one of my args. One of the struct fields is a dynamically generated six-digit pin -- I can't replicate the exact struct values from my test because the pin field is dynamic. But I need to ensure the other args are correct. So it gives me the option to do this:

```go
var wc sqlmock.WildcardArg
mock.ExpectQuery("insert into users").
	WithArgs(a.ID, eu.FirstName, eu.LastName, eu.Email.String(), wc).
	WillReturnRows(sqlmock.NewRows([]string{"id", "created"}).AddRow(55, "2015-06-03T13:42:23Z"))
```

In this case, the 5th argument will always pass but the first four have to match normally.

I'm testing this branch and have this functionality working locally, but took a look at master and the relevant code would work on both as it's just a few lines in argsMatches(). Let me know if this is something you'd be okay with and I'll submit a pull request against master that could be rebased against this branch.

**Comment by l3pp4rd** [comment]
@cristiangraz for that reason there is `sqlmock.Argument` interface with Match function. So you can match argument based on its type string and length to be 6 digits.

**Comment by cristiangraz** [comment]
@l3pp4rd That's great! Sorry -- not sure how I missed that.

**Comment by l3pp4rd** [comment]
@cristiangraz also concerning goroutines, the expectations could be matched in any order, but you should track with channel or with wait group for your routines to finish in order to pass a test and prevent loosing an error in case if that query fails in goroutine. If you do not wait for these queries to finish your tests will never pass unless they will not process faster than that goroutine.
In the end, it seems reasonable to allow expectations to be matched in different order.

**Comment by l3pp4rd** [comment]
@dgnorton it should be working as expected, could you show your test function source? there is a [similar test case](https://github.com/DATA-DOG/go-sqlmock/blob/refactor/sqlmock_test.go#L294)

**Comment by l3pp4rd** [comment]
@cristiangraz goroutine matching should be supported, see [test case](https://github.com/DATA-DOG/go-sqlmock/blob/refactor/sqlmock_test.go#L580)

**Pull request merged**
